### ISSUE TITLE
Configuration Management

### ISSUE THREAD

**Issue by dylanbernhardt** [dylanbernhardt/beatradar#4]
- [ ] 1. Create configuration file structure
- [ ] 2. Implement configuration loading from file
- [ ] 3. Add environment variable support
- [ ] 4. Create genre mapping configuration
- [ ] 5. Implement configuration validation
