### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by dylanbernhardt** [dylanbernhardt/beatradar#5]
- [ ] 1. Set up test environment
- [ ] 2. Create unit tests for scraper
- [ ] 3. Implement integration tests for API
- [ ] 4. Create mock objects for testing
- [ ] 5. Set up CI/CD pipeline for automated testing
